apiVersion: v1
kind: Service
metadata:
  name: game-of-life-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8090
    targetPort: 8080
    protocol: TCP
  selector:
    app: game-of-life